# Generated by Django 3.2.8 on 2021-10-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='Duration',
            field=models.DateTimeField(blank=True),
        ),
    ]
