# Generated by Django 3.2.8 on 2021-10-23 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioapp', '0003_subprogram_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='subprogram',
            name='artistname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
