# Generated by Django 3.2.8 on 2021-10-27 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioapp', '0005_auto_20211023_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='interview_status',
            field=models.BooleanField(default=False),
        ),
    ]
