# Generated by Django 3.2.8 on 2021-10-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioapp', '0006_program_interview_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('timeDuration', models.DateTimeField(blank=True)),
            ],
        ),
    ]
