# Generated by Django 3.2.8 on 2021-10-30 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioapp', '0007_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='audio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subprogram',
            name='subprogram_status',
            field=models.BooleanField(default=False),
        ),
    ]
