# Generated by Django 3.2.8 on 2021-10-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioapp', '0008_auto_20211030_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='price',
        ),
        migrations.AddField(
            model_name='subprogram',
            name='price',
            field=models.IntegerField(default='0'),
        ),
    ]
