# Generated by Django 3.2.8 on 2021-11-04 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioapp', '0011_alter_orderdetail_programid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='ProgramID',
            field=models.IntegerField(blank=True),
        ),
    ]
