# Generated by Django 3.2.8 on 2021-11-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioapp', '0012_alter_orderdetail_programid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subprogram',
            name='p_status',
            field=models.BooleanField(default=False),
        ),
    ]
